//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFIDentalClinic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DentalTreatment
    {
        public int Id { get; set; }
        public int PatientId { get; set; }
        public string CreatedDate { get; set; }
        public string Service { get; set; }
        public string ProcedureDetails { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
