//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFIDentalClinic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.DentalTreatments = new HashSet<DentalTreatment>();
        }
    
        public int Id { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Gender { get; set; }
        public string BirthDate { get; set; }
        public string MaritalStatus { get; set; }
        public string MobileNumber { get; set; }
        public string TelephoneNumber { get; set; }
        public bool Palate { get; set; }
        public bool BadBreath { get; set; }
        public bool BleedingInMouth { get; set; }
        public bool GumsColorChange { get; set; }
        public bool LumpsInMouth { get; set; }
        public bool TeethColorChange { get; set; }
        public bool SensitiveTeeth { get; set; }
        public bool ClickingSound { get; set; }
        public string PastDentalCareOrTreatments { get; set; }
        public string HeartAilmentOrDisease { get; set; }
        public string HospitalAdmission { get; set; }
        public string SelfMedication { get; set; }
        public string Allergies { get; set; }
        public string Operation { get; set; }
        public string TumorsOrGrowth { get; set; }
        public bool Diabetes { get; set; }
        public bool Sinusitis { get; set; }
        public bool BleedingGums { get; set; }
        public bool Hypertension { get; set; }
        public bool StomachDisease { get; set; }
        public bool BloodDisease { get; set; }
        public bool Headache { get; set; }
        public bool LiverDisease { get; set; }
        public string Pregnant { get; set; }
        public bool Cold { get; set; }
        public bool Kidney { get; set; }
        public string FamilyHistryOnAny { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DentalTreatment> DentalTreatments { get; set; }
    }
}
